name: mt-eval
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- accelerate=0.23.0
- bandit=1.7.5
- black=23.10.0
- ipykernel=6.25.2
- python=3.10
- pytorch==1.13.1
- pytorch-cuda=11.6
- torchaudio==0.13.1
- torchvision==0.14.1
- openai=0.28.1
- transformers=4.36.1
- sentencepiece=0.1.99
- nltk==3.8.1
- einops==0.7.0
- emoji==2.9.0
- langdetect==1.0.9
- tabulate=0.9.0
- seaborn=0.13.0
- pip
- pip:
  - rouge==1.0.1
  - strictfire==0.4.1
  - termcolor==2.3.0
  - transformers-stream-generator==0.0.4
  - fschat==0.2.34